import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Tarot",
  description: "Terms of Service for the Tarot reading app.",
};

export default function TermsPage() {
  return (
    <main className="legal-page container">
      <article className="legal-page__content">
        <h1>Terms of Service</h1>
        <p><em>Last updated: April 6, 2026</em></p>

        <p>
          Welcome to Tarot (&quot;the Service&quot;, &quot;we&quot;, &quot;us&quot;).
          By accessing or using the Service, you agree to be bound by these Terms
          of Service (&quot;Terms&quot;). If you do not agree, please do not use
          the Service.
        </p>

        <h2>1. Entertainment Only</h2>
        <p>
          The Service provides tarot card readings and related content strictly
          for entertainment purposes. Readings are not a substitute for
          professional advice, including but not limited to medical, legal,
          psychological, or financial advice. You are solely responsible for any
          decisions you make based on content generated by the Service.
        </p>

        <h2>2. Eligibility</h2>
        <p>
          You must be at least 16 years old to use the Service. By using the
          Service you represent that you meet this requirement.
        </p>

        <h2>3. Accounts</h2>
        <p>
          Some features require you to create an account. You agree to provide
          accurate information, keep your credentials secure, and notify us of
          any unauthorized use. You are responsible for all activity under your
          account. We may suspend or terminate accounts that violate these Terms.
        </p>

        <h2>4. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for any unlawful purpose;</li>
          <li>Attempt to disrupt, reverse-engineer, or gain unauthorized access to the Service;</li>
          <li>Upload malicious content or harass other users;</li>
          <li>Scrape, copy, or resell content from the Service without permission.</li>
        </ul>

        <h2>5. Intellectual Property</h2>
        <p>
          All content, design, text, graphics, and code on the Service are owned
          by us or our licensors and are protected by copyright and other laws.
          You receive a limited, non-exclusive, non-transferable license to use
          the Service for personal, non-commercial purposes.
        </p>

        <h2>6. User Content</h2>
        <p>
          If you submit content (questions, notes, feedback), you grant us a
          worldwide, royalty-free license to use, store, and display it solely
          for the purpose of operating and improving the Service.
        </p>

        <h2>7. Disclaimers</h2>
        <p>
          The Service is provided &quot;as is&quot; without warranties of any
          kind. We do not guarantee accuracy, availability, or fitness for a
          particular purpose. Tarot readings are generated for entertainment and
          carry no predictive guarantee.
        </p>

        <h2>8. Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by law, we shall not be liable for any
          indirect, incidental, special, or consequential damages arising out of
          your use of the Service. Our total liability shall not exceed the
          amount you paid us in the twelve months preceding the claim, or EUR 50
          if you paid nothing.
        </p>

        <h2>9. Changes to the Service or Terms</h2>
        <p>
          We may modify the Service or these Terms at any time. Material changes
          will be announced on this page with an updated &quot;last updated&quot;
          date. Continued use after changes constitutes acceptance.
        </p>

        <h2>10. Termination</h2>
        <p>
          You may stop using the Service at any time. We may suspend or
          terminate your access if you violate these Terms.
        </p>

        <h2>11. Governing Law</h2>
        <p>
          These Terms are governed by the laws of the European Union and the
          country where the Service operator is established, without regard to
          conflict-of-law principles. EU consumers retain the protections of
          their local mandatory law.
        </p>

        <h2>12. Contact</h2>
        <p>
          For questions about these Terms, contact us at{" "}
          <a href="mailto:support@example.com">support@example.com</a>.
        </p>

        <p>
          <Link href="/">← Back to home</Link>
        </p>

        <hr />
        <p>
          <small>
            <strong>Note:</strong> This is a draft template and not legal advice.
            Please have it reviewed by a qualified lawyer before launch.
          </small>
        </p>
      </article>
    </main>
  );
}
